volumes:
  postgres-volume:
  timescale-volume:
  redis-volume:
  minio-volume:

services:
  umbrella:
    build:
      context: .
      target: test
    tty: true
    depends_on:
      - postgres
      - redis
      - minio
      - timescale
      - mailhog
    volumes:
      - ./apps/codecov-api/:/app/apps/codecov-api/
      - ./apps/worker/:/app/apps/worker/
      - ./libs/shared/:/app/libs/shared/
      - ./codecov.test.yml:/config/codecov.yml

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
        tmpfs:
          size: 1024M

  redis:
    image: redis:6-alpine
    volumes:
      - redis-volume:/data

  minio:
    image: minio/minio:latest
    command: server /export
    ports:
      - "${MINIO_PORT:-9000}:9000"
    environment:
      - MINIO_ACCESS_KEY=codecov-default-key
      - MINIO_SECRET_KEY=codecov-default-secret
    volumes:
      - minio-volume:/export

  timescale:
    image: timescale/timescaledb:latest-pg14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
        tmpfs:
          size: 1024M

  mailhog:
    image: mailhog/mailhog:latest
