volumes:
  postgres-volume:
  timescale-volume:
  minio-volume:

services:
  umbrella:
    build:
      context: .
      target: test
    tty: true
    depends_on:
      - postgres
      - redis
      - minio
      - timescale
      - mailhog
    volumes:
      - ./apps/codecov-api/:/app/apps/codecov-api/
      - ./apps/worker/:/app/apps/worker/
      - ./libs/shared/:/app/libs/shared/
      - ./codecov.test.yml:/config/codecov.yml

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
        tmpfs:
          size: 1024M

  redis:
    image: redis:6-alpine

  minio:
    image: minio/minio:latest
    command: server /export
    environment:
      - MINIO_ACCESS_KEY=codecov-default-key
      - MINIO_SECRET_KEY=codecov-default-secret
    volumes:
      - minio-volume:/export

  timescale:
    image: timescale/timescaledb-ha:pg14-latest
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  mailhog:
    image: mailhog/mailhog:latest
