[dependency-groups]
dev = [
    # global dev dependencies
    "mypy>=1.15.0",
    "pre-commit>=4.2.0",
    "ruff>=0.11.8",
]

[tool.uv.workspace]
members = ["apps/*", "libs/*"]

[tool.uv.sources]
shared = { workspace = true }
