# Generated by Django 4.2.21 on 2025-08-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codecov_auth", "0071_alter_invoicebilling_account_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnerToBeDeleted",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner_id", models.IntegerField()),
            ],
        ),
    ]
