# Generated by Django 4.2.20 on 2025-07-03 20:55

from django.contrib.postgres.operations import CreateCollation
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("codecov_auth", "0071_alter_invoicebilling_account_and_more"),
    ]

    operations = [
        # Ref: https://www.postgresql.org/docs/current/collation.html#COLLATION-NONDETERMINISTIC
        CreateCollation(
            "case_insensitive",
            provider="icu",
            locale="und-u-ks-level2",
            deterministic=False,
        ),
    ]
