# Generated by Django 4.2.21 on 2025-08-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codecov_auth", "0072_ownertobedeleted"),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TYPE service ADD VALUE IF NOT EXISTS 'to_be_deleted';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="owner",
            name="service",
            field=models.TextField(
                choices=[
                    ("github", "Github"),
                    ("gitlab", "Gitlab"),
                    ("bitbucket", "Bitbucket"),
                    ("github_enterprise", "Github Enterprise"),
                    ("gitlab_enterprise", "Gitlab Enterprise"),
                    ("bitbucket_server", "Bitbucket Server"),
                    ("to_be_deleted", "To Be Deleted"),
                ]
            ),
        ),
    ]
