# Generated by Django 4.2.20 on 2025-07-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("codecov_auth", "0072_case_insensitive_collation")]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="username",
            field=models.TextField(
                db_collation="case_insensitive", null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.TextField(db_collation="case_insensitive", null=True),
        ),
    ]
