# Generated by Django 4.2.27 on 2026-06-05 00:00

from django.db import migrations, models

from shared.django_apps.migration_utils import RiskyAddField


class Migration(migrations.Migration):
    """
    BEGIN;
    --
    -- Add field support_pin to owner
    --
    ALTER TABLE "owners" ADD COLUMN "support_pin" varchar(6) DEFAULT '000000' NULL;
    COMMIT;
    """

    dependencies = [
        ("codecov_auth", "0074_ownerexport"),
    ]

    operations = [
        # Add the column with the cheap "000000" placeholder default. A constant
        # default is a metadata-only change in Postgres, so existing rows are not
        # rewritten. Real random PINs are assigned out of band by the
        # `backfill_support_pins` management command.
        RiskyAddField(
            model_name="owner",
            name="support_pin",
            field=models.CharField(
                blank=True, default="000000", max_length=6, null=True
            ),
        ),
    ]
