# Generated by Django 4.2.27 on 2026-06-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    """Switch the support_pin default to the cheap "000000" placeholder.

    This only changes the Django-level default, so there is no DDL and no table
    rewrite. Existing rows are untouched; the `backfill_support_pins` management
    command assigns real random PINs in batches.
    """

    dependencies = [
        ("codecov_auth", "0075_owner_support_pin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="support_pin",
            field=models.CharField(
                blank=True, default="000000", max_length=6, null=True
            ),
        ),
    ]
