# Generated by Django 4.2.30 on 2026-08-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codecov_auth", "0079_ownertobedeleted_requested_by_and_on_hold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="plan",
            field=models.TextField(default="users-developer", null=True),
        ),
    ]
