.PHONY: devenv.test.worker
devenv.test.worker:
	docker compose exec --workdir /app/apps/worker umbrella pytest --rootdir=/app --cov=/app --cov-report=xml:coverage.xml --junitxml=junit.xml -o junit_family=legacy

.PHONY: devenv.test.api
devenv.test.api:
	docker compose exec --workdir /app/apps/codecov-api umbrella pytest --rootdir=/app --cov=/app --cov-report=xml:coverage.xml --junitxml=junit.xml -o junit_family=legacy

.PHONY: devenv.test.shared
devenv.test.shared:
	docker compose exec --workdir /app/libs/shared umbrella pytest --rootdir=/app --cov=/app --cov-report=xml:coverage.xml --junitxml=junit.xml -o junit_family=legacy

.PHONY: devenv.upload.worker
devenv.upload.worker:
	./tools/devenv/scripts/codecovcli-helper.sh upload-process -f apps/worker/coverage.xml --disable-search -F workerunit
	./tools/devenv/scripts/codecovcli-helper.sh upload-process --report-type test_results -f apps/worker/junit.xml --disable-search -F workerunit

.PHONY: devenv.upload.api
devenv.upload.api:
	./tools/devenv/scripts/codecovcli-helper.sh upload-process -f apps/codecov-api/coverage.xml --disable-search -F apiunit
	./tools/devenv/scripts/codecovcli-helper.sh upload-process --report-type test_results -f apps/codecov-api/junit.xml --disable-search -F apiunit

.PHONY: devenv.upload.shared
devenv.upload.shared:
	./tools/devenv/scripts/codecovcli-helper.sh upload-process -f libs/shared/tests/coverage.xml --disable-search -F sharedunit
	./tools/devenv/scripts/codecovcli-helper.sh upload-process --report-type test_results -f libs/shared/tests/junit.xml --disable-search -F sharedunit

