# Generated by Django 4.2.20 on 2025-07-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("legacy_migrations", "0008_delete_pull_update_trigger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yamlhistory",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
