# Generated by Django on 2025-11-25
# Fix for TriggeredDataChangeViolation: exclude current row from inner UPDATE

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("legacy_migrations", "0009_delete_yamlhistory"),
    ]

    operations = [
        migrations.RunSQL(
            """
            create or replace function owners_before_insert_or_update() returns trigger as $$
            begin
                -- user has changed name or deleted and invalidate sessions
                with _owners as (update owners
                                set username = null
                                where service = new.service
                                and username = new.username::citext
                                and ownerid is distinct from new.ownerid
                                returning ownerid)
                delete from sessions where ownerid in (select ownerid from _owners);
                return new;
            end;
            $$ language plpgsql;
            """
        ),
    ]