# Generated by Django 4.2.20 on 2025-07-04 14:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("legacy_migrations", "0009_delete_yamlhistory"),
    ]

    run_before = [
        ("codecov_auth", "0073_alter_owner_username_alter_user_email"),
        ("core", "0072_alter_repository_name"),
    ]

    operations = [
        migrations.RunSQL(
            # Drop the triggers temporarily so that we can alter the username
            # field on the owners table and the name field on the repos table.
            """
            DROP TRIGGER IF EXISTS owners_before_update ON owners;
            DROP TRIGGER IF EXISTS repos_before_update ON repos;
            """
        ),
    ]
