# Generated by Django 4.2.20 on 2025-07-03 19:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("legacy_migrations", "0009_alter_yamlhistory_id"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name="yamlhistory",
                    new_name="yaml_history_ownerid_timestamp",
                    old_name="yaml_histor_ownerid_74e79b_idx",
                ),
            ],
        ),
    ]
