# Generated by Django on 2025-12-09
# Fix for TriggeredDataChangeViolation: convert BEFORE trigger to AFTER trigger
# BEFORE triggers cannot modify the same table they are triggered on

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("legacy_migrations", "0010_fix_owners_trigger_self_modification"),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Drop existing BEFORE triggers
            drop trigger if exists owners_before_insert on owners;
            drop trigger if exists owners_before_update on owners;
            
            -- Create the renamed function (AFTER instead of BEFORE)
            create or replace function owners_after_insert_or_update() returns trigger as $$
            begin
                -- user has changed name or deleted and invalidate sessions
                with _owners as (update owners
                                set username = null
                                where service = new.service
                                and username = new.username::citext
                                and ownerid is distinct from new.ownerid
                                returning ownerid)
                delete from sessions where ownerid in (select ownerid from _owners);
                return new;
            end;
            $$ language plpgsql;
            
            -- Recreate as AFTER triggers using the renamed function
            create trigger owners_after_insert after insert on owners
            for each row
            execute procedure owners_after_insert_or_update();

            create trigger owners_after_update after update on owners
            for each row
            when (new.username is not null and new.username is distinct from old.username)
            execute procedure owners_after_insert_or_update();
            """
        ),
    ]
