# Generated by Django 4.2.14 on 2024-08-07 13:35

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.db import migrations

from shared.django_apps.migration_utils import RiskyRunSQL


class Migration(migrations.Migration):
    """
    BEGIN;
    --
    -- Create index name_trgm_idx on OpClass(Upper(F(name)), name=gin_trgm_ops) on model branch
    --
    CREATE INDEX "name_trgm_idx" ON "branches" USING gin ((UPPER("branch")) gin_trgm_ops);
    COMMIT;
    """

    dependencies = [
        ("core", "0055_increment_version"),
    ]

    operations = [
        # SeparateDatabaseAndState is used here because GinIndex(OpClass(...)) codegen
        # broke in Django 5.x: it places the operator class inside the expression parens
        # instead of after them, producing invalid SQL. The correct SQL is hardcoded in
        # the database_operations; state_operations keep Django's model state in sync.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                RiskyRunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "name_trgm_idx" ON "branches" USING gin ((UPPER("name")) gin_trgm_ops)',
                    reverse_sql='DROP INDEX IF EXISTS "name_trgm_idx"',
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name="branch",
                    index=django.contrib.postgres.indexes.GinIndex(
                        django.contrib.postgres.indexes.OpClass(
                            django.db.models.functions.text.Upper("name"),
                            name="gin_trgm_ops",
                        ),
                        name="name_trgm_idx",
                    ),
                ),
            ],
        ),
    ]
