# Generated by Django 4.2.20 on 2025-07-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codecov_auth", "0072_case_insensitive_collation"),
        ("core", "0071_pull_sentry_commentid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repository",
            name="name",
            field=models.TextField(db_collation="case_insensitive"),
        ),
    ]
