# Generated by Django 4.2.21 on 2025-08-05 21:05

from django.db import migrations


def update_version(apps, schema):
    Constants = apps.get_model("core", "Constants")
    version = Constants.objects.get(key="version")
    version.value = "25.8.5"
    version.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0073_increment_version"),
    ]

    operations = [migrations.RunPython(update_version)]
