# Generated by Django 4.2.21 on 2025-10-06 16:40

from django.db import migrations


def update_version(apps, schema):
    Constants = apps.get_model("core", "Constants")
    version = Constants.objects.get(key="version")
    version.value = "25.10.6"
    version.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0074_increment_version"),
    ]

    operations = [migrations.RunPython(update_version)]
