# Generated by Django 4.2.25 on 2025-12-01 23:23

from django.db import migrations


def update_version(apps, schema):
    Constants = apps.get_model("core", "Constants")
    version = Constants.objects.get(key="version")
    version.value = "25.12.1"
    version.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0076_increment_version"),
    ]

    operations = [migrations.RunPython(update_version)]
