# Generated by Django 4.2.25 on 2025-12-04 01:26

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.db import migrations

from shared.django_apps.migration_utils import RiskyAddIndex


class Migration(migrations.Migration):
    """
    BEGIN;
    --
    -- Create index repos_name_trgm_idx on OpClass(Upper(F(name)), name=gin_trgm_ops) on model repository
    --
    CREATE INDEX "repos_name_trgm_idx" ON "repos" USING gin ((UPPER("name")) gin_trgm_ops);
    COMMIT;
    """

    dependencies = [
        ("core", "0076_increment_version"),
    ]

    operations = [
        RiskyAddIndex(
            model_name="repository",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper("name"), name="gin_trgm_ops"
                ),
                name="repos_name_trgm_idx",
            ),
        ),
    ]
