# Generated by Django 4.2.27 on 2026-01-08 21:39

from django.db import migrations


def update_version(apps, schema):
    Constants = apps.get_model("core", "Constants")
    version = Constants.objects.get(key="version")
    version.value = "26.1.8"
    version.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0077_increment_version"),
    ]

    operations = [migrations.RunPython(update_version)]
