# Generated by Django 4.2.27 on 2026-02-02 19:39

from django.db import migrations


def update_version(apps, schema):
    Constants = apps.get_model("core", "Constants")
    version = Constants.objects.get(key="version")
    version.value = "26.2.2"
    version.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0080_repository_repos_name_trgm_idx"),
    ]

    operations = [migrations.RunPython(update_version)]
