# Generated by Django 4.2.27 on 2026-03-04 22:05

from django.db import migrations


def update_version(apps, schema):
    Constants = apps.get_model("core", "Constants")
    version = Constants.objects.get(key="version")
    version.value = "26.3.4"
    version.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0082_commiterror_commit_id_idx"),
    ]

    operations = [migrations.RunPython(update_version)]
