# Generated by Django 4.2.27 on 2026-05-19 22:50

from django.db import migrations


def update_version(apps, schema):
    Constants = apps.get_model("core", "Constants")
    version = Constants.objects.get(key="version")
    version.value = "26.5.18"
    version.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0084_increment_version"),
    ]

    operations = [migrations.RunPython(update_version)]
