# Generated by Django 4.2.21 on 2025-09-08 14:48

from shared.django_apps.migration_utils import RiskyAddConstraint

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0042_alter_testflagbridge_id'),
    ]

    operations = [
        RiskyAddConstraint(
            model_name='commitreport',
            constraint=models.UniqueConstraint(fields=('commit', 'code'), name='reports_commitreport_commit_code_unique'),
        ),
    ]
