# Generated by Django 4.2.21 on 2025-09-10 18:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0042_alter_testflagbridge_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flake",
            name="reduced_error",
        ),
        migrations.RemoveField(
            model_name="flake",
            name="repository",
        ),
        migrations.RemoveField(
            model_name="flake",
            name="test",
        ),
        migrations.RemoveField(
            model_name="lastcacherollupdate",
            name="repository",
        ),
        migrations.RemoveField(
            model_name="reducederror",
            name="repository",
        ),
        migrations.RemoveField(
            model_name="test",
            name="repository",
        ),
        migrations.RemoveField(
            model_name="testflagbridge",
            name="flag",
        ),
        migrations.RemoveField(
            model_name="testflagbridge",
            name="test",
        ),
        migrations.RemoveField(
            model_name="testinstance",
            name="reduced_error",
        ),
        migrations.RemoveField(
            model_name="testinstance",
            name="test",
        ),
        migrations.RemoveField(
            model_name="testinstance",
            name="upload",
        ),
        migrations.RemoveField(
            model_name="testresultreporttotals",
            name="report",
        ),
        migrations.DeleteModel(
            name="DailyTestRollup",
        ),
        migrations.DeleteModel(
            name="Flake",
        ),
        migrations.DeleteModel(
            name="LastCacheRollupDate",
        ),
        migrations.DeleteModel(
            name="ReducedError",
        ),
        migrations.DeleteModel(
            name="Test",
        ),
        migrations.DeleteModel(
            name="TestFlagBridge",
        ),
        migrations.DeleteModel(
            name="TestInstance",
        ),
        migrations.DeleteModel(
            name="TestResultReportTotals",
        ),
    ]
