version: "3.3"
services:
  livegrep-backend-codecov:
    image: "docker.io/livegrep/base:${image_version:-latest}"
    command:
      - "/livegrep/bin/codesearch"
      - "-grpc=0.0.0.0:9898"
      - "-load_index=/data/codecov-index.idx"
      - "-debug=profile,index"
      - "-threads=4"
    ports:
      - "9898:9898"
    volumes:
      - livegrep-data:/data
    restart: unless-stopped

  livegrep-backend-sentry:
    image: "docker.io/livegrep/base:${image_version:-latest}"
    command:
      - "/livegrep/bin/codesearch"
      - "-grpc=0.0.0.0:9898"
      - "-load_index=/data/sentry-index.idx"
      - "-debug=profile,index"
      - "-threads=4"
    ports:
      - "9899:9898"
    volumes:
      - livegrep-data:/data
    restart: unless-stopped

  livegrep-frontend:
    image: "docker.io/livegrep/base:${image_version:-latest}"
    command:
      - "/livegrep/bin/livegrep"
      - "-docroot"
      - "/livegrep/web/"
      - "/conf/livegrep.json"
    ports:
      - "8910:8910"
    volumes:
      - type: bind
        source: ./conf
        target: /conf
        read_only: true
    restart: unless-stopped
volumes:
  livegrep-data:
