# Generated by Django 4.2.20 on 2025-06-10 21:35

from django.db import migrations, models

from shared.django_apps.migration_utils import RiskyAddIndex, RiskyRunSQL


class Migration(migrations.Migration):
    dependencies = [
        ("ta_timeseries", "0010_auto_20250528_1540"),
    ]

    operations = [
        RiskyRunSQL(
            """
                DROP INDEX IF EXISTS ta_ts__branch_i;
            """,
        ),
        RiskyRunSQL(
            """
                DROP INDEX IF EXISTS ta_ts__test_i;
            """,
        ),
        RiskyAddIndex(
            model_name="testrun",
            index=models.Index(
                fields=["upload_id", "outcome", "test_id"],
                name="ta_ts_upload_outcome_test_idx",
            ),
        ),
        RiskyRunSQL(
            """
                CREATE INDEX IF NOT EXISTS ta_ts_summary_repo_ts_idx
                ON ta_timeseries_testrun_summary_1day (repo_id, timestamp_bin DESC);
            """,
        ),
        RiskyRunSQL(
            """
                CREATE INDEX IF NOT EXISTS ta_ts_branch_summary_repo_ts_idx
                ON ta_timeseries_testrun_branch_summary_1day (repo_id, branch, timestamp_bin DESC);
            """,
        ),
    ]
