# Generated by Django 4.2.20 on 2025-01-XX XX:XX

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ta_timeseries", "0015_drop_materialized_hypertable_indexes"),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER MATERIALIZED VIEW ta_timeseries_testrun_summary_1day 
            SET (timescaledb.materialized_only = false);
            """,
            reverse_sql="""
            ALTER MATERIALIZED VIEW ta_timeseries_testrun_summary_1day 
            SET (timescaledb.materialized_only = true);
            """,
        ),
        migrations.RunSQL(
            """
            ALTER MATERIALIZED VIEW ta_timeseries_testrun_branch_summary_1day 
            SET (timescaledb.materialized_only = false);
            """,
            reverse_sql="""
            ALTER MATERIALIZED VIEW ta_timeseries_testrun_branch_summary_1day 
            SET (timescaledb.materialized_only = true);
            """,
        ),
    ]
