# Generated by Django 4.2.21 on 2025-07-25 20:29

import django.contrib.postgres.fields
import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ta_timeseries", "0027_refresh_test_aggregate_daily_cas"),
    ]

    operations = [
        migrations.CreateModel(
            name="BranchTestAggregateDaily",
            fields=[
                (
                    "timestamp_bin",
                    models.DateTimeField(primary_key=True, serialize=False),
                ),
                ("repo_id", models.IntegerField()),
                ("branch", models.TextField()),
                ("name", models.TextField()),
                ("classname", models.TextField()),
                ("testsuite", models.TextField()),
                ("computed_name", models.TextField()),
                (
                    "failing_commits",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), null=True, size=None
                    ),
                ),
                ("avg_duration_seconds", models.FloatField()),
                ("last_duration_seconds", models.FloatField()),
                ("pass_count", models.IntegerField()),
                ("fail_count", models.IntegerField()),
                ("skip_count", models.IntegerField()),
                ("flaky_fail_count", models.IntegerField()),
                ("updated_at", models.DateTimeField()),
                (
                    "flags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), null=True, size=None
                    ),
                ),
            ],
            options={
                "db_table": "ta_timeseries_branch_test_aggregate_daily",
                "managed": False,
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin(
                    "ta_timeseries.branch_test_aggregate_daily"
                ),
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="TestAggregateDaily",
            fields=[
                (
                    "timestamp_bin",
                    models.DateTimeField(primary_key=True, serialize=False),
                ),
                ("repo_id", models.IntegerField()),
                ("name", models.TextField()),
                ("classname", models.TextField()),
                ("testsuite", models.TextField()),
                ("computed_name", models.TextField()),
                ("failing_commits", models.IntegerField()),
                ("avg_duration_seconds", models.FloatField()),
                ("last_duration_seconds", models.FloatField()),
                ("pass_count", models.IntegerField()),
                ("fail_count", models.IntegerField()),
                ("skip_count", models.IntegerField()),
                ("flaky_fail_count", models.IntegerField()),
                ("updated_at", models.DateTimeField()),
                (
                    "flags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), null=True, size=None
                    ),
                ),
            ],
            options={
                "db_table": "ta_timeseries_test_aggregate_daily",
                "managed": False,
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin(
                    "ta_timeseries.test_aggregate_daily"
                ),
                models.Model,
            ),
        ),
    ]
