# Generated by Django 4.2.21 on 2025-08-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ta_timeseries", "0031_redefine_test_aggregate_dailies_by_test_id"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
                    model_name="testrun",
                    index=models.Index(
                        fields=["repo_id", "test_id", "timestamp"],
                        name="ta_ts__repo_test_time_idx",
                    ),
                ),
            ],
        ),
    ]
