# Generated by Django for adding TTL column to testrun table

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ta_timeseries", "0034_remove_old_summary_caggs"),
    ]

    operations = [
        migrations.AddField(
            model_name="testrun",
            name="ttl",
            field=models.DateTimeField(null=True),
        ),
    ]
