# Generated by Django 4.2.21 on 2025-10-22 00:00

from django.db import migrations, models

from shared.django_apps.migration_utils import RiskyAddIndex


class Migration(migrations.Migration):
    dependencies = [
        ("ta_timeseries", "0035_alter_branch_test_aggregate_daily_policy"),
    ]

    operations = [
        RiskyAddIndex(
            model_name="testrun",
            index=models.Index(fields=["repo_id"], name="ta_ts__repo_id_idx"),
        ),
    ]
