type ImpactedFile {
  name: String @deprecated(reason: "Use fileName instead")
  fileName: String
  baseName: String
  headName: String
  isNewFile: Boolean!
  isRenamedFile: Boolean!
  isDeletedFile: Boolean!
  baseCoverage: CoverageTotals
  headCoverage: CoverageTotals
  patchCoverage: CoverageTotals
  patchTotals: CoverageTotals @deprecated(reason: "Use patchCoverage instead")
  changeCoverage: Float
  missesCount: Int!
  hashedPath: String!
  segments(filters: SegmentsFilters): SegmentsResult!
}

type ImpactedFiles {
  results: [ImpactedFile]
}

union ImpactedFilesResult =
    ImpactedFiles
  | UnknownFlags
