# Generated by Django 4.2.21 on 2025-08-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_analytics", "0002_flake_flags_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PullComment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("repo_id", models.BigIntegerField()),
                ("pull_id", models.IntegerField()),
                ("comment_id", models.TextField(null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["repo_id", "pull_id"],
                        name="ta_pr_comment_repo_pull_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="pullcomment",
            constraint=models.UniqueConstraint(
                fields=("repo_id", "pull_id"), name="ta_pr_comment_repo_pull"
            ),
        ),
    ]
