# Generated by Django 4.2.20 on 2025-08-15 16:23

import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_analytics", "0003_pullcomment_pullcomment_ta_pr_comment_repo_pull"),
    ]

    operations = [
        migrations.CreateModel(
            name="TAUpload",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("repo_id", models.BigIntegerField()),
            ],
            options={
                "db_table": "test_analytics_upload",
                "indexes": [
                    models.Index(fields=["repo_id"], name="ta_upload_repo_idx"),
                    models.Index(fields=["created_at"], name="ta_upload_time_idx"),
                    models.Index(
                        fields=["repo_id", "created_at"], name="ta_upload_repo_time_idx"
                    ),
                ],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin(
                    "test_analytics.taupload"
                ),
                models.Model,
            ),
        ),
    ]
