# Generated by Django 4.2.21 on 2025-08-15 15:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("test_analytics", "0004_taupload"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PullComment",
            new_name="TAPullComment",
        ),
    ]
