# Generated by Django 4.2.21 on 2025-08-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_analytics", "0005_rename_pullcomment_tapullcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="taupload",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("processed", "processed"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="taupload",
            name="task_token",
            field=models.CharField(max_length=36, null=True),
        ),
    ]
