# Generated by Django 4.2.20 on 2025-08-14 14:06

from django.db import migrations, models

from shared.django_apps.migration_utils import RiskyAddIndex


class Migration(migrations.Migration):
    dependencies = [
        ("upload_breadcrumbs", "0001_initial"),
    ]

    operations = [
        RiskyAddIndex(
            model_name="uploadbreadcrumb",
            index=models.Index(
                fields=["-created_at", "-id"], name="upload_breadcrumbs_created_id"
            ),
        ),
    ]
