# Generated by Django 4.2.21 on 2025-08-27 19:33

from django.db import migrations, models

from shared.django_apps.migration_utils import RiskyAddIndex, RiskyRemoveIndex


class Migration(migrations.Migration):
    dependencies = [
        ("upload_breadcrumbs", "0002_uploadbreadcrumb_upload_breadcrumbs_created_id"),
    ]

    operations = [
        RiskyRemoveIndex(
            model_name="uploadbreadcrumb",
            name="upload_breadcrumbs_sha_repo",
        ),
        RiskyAddIndex(
            model_name="uploadbreadcrumb",
            index=models.Index(
                fields=["sentry_trace_id"], name="upload_breadcrumbs_sentry_trc"
            ),
        ),
        RiskyAddIndex(
            model_name="uploadbreadcrumb",
            index=models.Index(
                fields=["repo_id", "commit_sha"], name="upload_breadcrumbs_repo_sha"
            ),
        ),
    ]
