name: Run Lint

on:
  workflow_call:
    inputs:
      make_target_prefix:
        type: string
        default: ""

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: make ${{ inputs.make_target_prefix }}lint.install
      - name: Check
        run: make ${{ inputs.make_target_prefix }}lint.check

