name: CI

on:
  push:
    tags:
      - prod-*
      - stage-*
    branches:
      - main
      - staging
  pull_request:
  merge_group:

permissions:
  actions: "write"
  contents: "read"
  id-token: "write"
  issues: "write"
  pull-requests: "write"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3

  change-detection:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      worker: ${{ steps.filter.outputs.worker }}
      codecov-api: ${{ steps.filter.outputs.codecov-api }}
      shared: ${{ steps.filter.outputs.shared }}
    steps:
      # Checking out is not necessary for PRs but it is otherwise
      - uses: actions/checkout@v4
        if: ${{ github.event_name != 'pull_request' }}
        with:
          submodules: 'recursive'
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          # As long as worker/api/shared are submodules, we should include
          # patterns that match the submodule placeholder to be sure submodule
          # updates will trigger the right workflows.
          filters: |
            worker:
              - 'apps/worker'
              - 'apps/worker/**'
              - 'libs/shared'
              - 'libs/shared/**'
              - '.github/workflows/worker-ci.yml'
            codecov-api:
              - 'apps/codecov-api'
              - 'apps/codecov-api/**'
              - 'libs/shared'
              - 'libs/shared/**'
              - '.github/workflows/api-ci.yml'
            shared:
              - 'libs/shared'
              - 'libs/shared/**'
              - '.github/workflows/shared-ci.yml'

  reqs:
    name: Build Requirements
    uses: ./.github/workflows/_build-requirements.yml
    secrets: inherit

  api-ci:
    name: API CI
    needs: [change-detection, reqs]
    runs-on: ubuntu-latest
    steps:
      # By using the `gh` cli to dispatch these workflows instead of a `uses:`-style
      # job, we effectively reset GHA's limit of 20 workflow calls and give this workflow
      # its own quota.
      - name: Dispatch
        run: |
          gh workflow run api-ci.yml \
            --repo ${{ github.repository }} \
            --ref ${{ github.event.pull_request.head.ref || github.event.merge_group.head_ref || github.ref }} \
            -f event_name='${{ github.event_name }}' \
            -f has_changes='${{ needs.change-detection.outputs.codecov-api == 'true' }}'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  worker-ci:
    name: Worker CI
    needs: [change-detection, reqs]
    runs-on: ubuntu-latest
    steps:
      # By using the `gh` cli to dispatch these workflows instead of a `uses:`-style
      # job, we effectively reset GHA's limit of 20 workflow calls and give this workflow
      # its own quota.
      - name: Dispatch
        run: |
          gh workflow run worker-ci.yml \
            --repo ${{ github.repository }} \
            --ref ${{ github.event.pull_request.head.ref || github.event.merge_group.head_ref || github.ref }} \
            -f event_name='${{ github.event_name }}' \
            -f has_changes='${{ needs.change-detection.outputs.worker == 'true' }}'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  shared-ci:
    name: Shared CI
    needs: [change-detection, reqs]
    runs-on: ubuntu-latest
    steps:
      # By using the `gh` cli to dispatch these workflows instead of a `uses:`-style
      # job, we effectively reset GHA's limit of 20 workflow calls and give this workflow
      # its own quota.
      - name: Dispatch
        run: |
          gh workflow run shared-ci.yml \
            --repo ${{ github.repository }} \
            --ref ${{ github.event.pull_request.head.ref || github.event.merge_group.head_ref || github.ref }} \
            -f event_name='${{ github.event_name }}' \
            -f has_changes='${{ needs.change-detection.outputs.shared == 'true' }}'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
