name: Create Self Hosted Release

on:
  pull_request:
    branches:
      - main
    types: [closed]

permissions:
  contents: "read"
  id-token: "write"

jobs:
  create-release:
    name: Tag Release ${{ github.head_ref }} and Push Docker image to Docker Hub
    if: ${{ github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/') && github.repository_owner == 'codecov' }}
    uses: codecov/gha-workflows/.github/workflows/create-release.yml@v1.2.21
    with:
      tag_to_prepend: self-hosted-
    secrets: inherit

  # Once we cut over to umbrella, we can just replace the default cache key in build-app.yml
  # and self-hosted.yml and get rid of this step.
  compute-reqs-cache-keys:
    name: Compute cache keys for requirements images
    runs-on: ubuntu-latest
    outputs:
      api-reqs-cache-key: ${{ steps.compute.outputs.api-cache-key }}
      worker-reqs-cache-key: ${{ steps.compute.outputs.worker-cache-key }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - id: compute
        run: |
          echo api-cache-key=${{ hashFiles('apps/codecov-api/uv.lock') }}-${{ hashFiles('docker/Dockerfile.requirements') }}-${{ hashFiles('libs/shared/**') }} >> "$GITHUB_OUTPUT"
          echo worker-cache-key=${{ hashFiles('apps/worker/uv.lock') }}-${{ hashFiles('docker/Dockerfile.requirements') }}-${{ hashFiles('libs/shared/**') }} >> "$GITHUB_OUTPUT"

  push-worker-image:
    needs: [create-release]
    if: ${{ github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/') && github.repository_owner == 'codecov' }}
    uses: codecov/gha-workflows/.github/workflows/self-hosted.yml@v1.2.36
    secrets: inherit
    with:
      push_release: true
      repo: ${{ vars.CODECOV_WORKER_IMAGE_V2 || vars.CODECOV_WORKER_IMAGE_V2_SELF_HOSTED || 'codecov/self-hosted-worker' }}
      output_directory: apps/worker
      make_target_prefix: worker.
      reqs_cache_key: ${{ needs.compute-reqs-cache-keys.outputs.worker-reqs-cache-key }}

  push-api-image:
    needs: [create-release]
    if: ${{ github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/') && github.repository_owner == 'codecov' }}
    uses: codecov/gha-workflows/.github/workflows/self-hosted.yml@v1.2.36
    secrets: inherit
    with:
      push_release: true
      repo: ${{ vars.CODECOV_API_IMAGE_V2 || vars.CODECOV_API_IMAGE_V2_SELF_HOSTED || 'codecov/self-hosted-api' }}
      output_directory: apps/codecov-api
      make_target_prefix: api.
      reqs_cache_key: ${{ needs.compute-reqs-cache-keys.outputs.api-reqs-cache-key }}
