name: Create Self Hosted Release PR

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: "Name of version  (ie 23.9.5)"
        required: true

jobs:
  create-release-pr:
    name: Create PR for Release ${{ github.event.inputs.versionName }}
    uses: ./.github/workflows/_create-release-pr.yml
    secrets: inherit
