name: Create Self Hosted Release

on:
  pull_request:
    branches:
      - main
    types: [closed]

permissions:
  contents: "read"
  id-token: "write"

jobs:
  create-release:
    name: Tag Release ${{ github.head_ref }} and Push Docker image to Docker Hub
    if: ${{ github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/') && github.repository_owner == 'codecov' }}
    uses: ./.github/workflows/_create-release.yml
    with:
      tag_to_prepend: self-hosted-
    secrets: inherit

  push-worker-image:
    needs: [create-release]
    if: ${{ github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/') && github.repository_owner == 'codecov' }}
    uses: ./.github/workflows/_self-hosted.yml
    secrets: inherit
    with:
      push_release: true
      repo: ${{ vars.CODECOV_WORKER_IMAGE_V2 || vars.CODECOV_WORKER_IMAGE_V2_SELF_HOSTED || 'codecov/self-hosted-worker' }}
      output_directory: apps/worker
      make_target_prefix: worker.

  push-api-image:
    needs: [create-release]
    if: ${{ github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/') && github.repository_owner == 'codecov' }}
    uses: ./.github/workflows/_self-hosted.yml
    secrets: inherit
    with:
      push_release: true
      repo: ${{ vars.CODECOV_API_IMAGE_V2 || vars.CODECOV_API_IMAGE_V2_SELF_HOSTED || 'codecov/self-hosted-api' }}
      output_directory: apps/codecov-api
      make_target_prefix: api.
