name: Shared CI

on:
  push:
    branches:
      - main
      - staging
    paths:
      - 'libs/shared/**'
      - '.github/workflows/shared-ci.yml'
  pull_request:

permissions:
    contents: read

jobs:
  shared-benchmark:
    name: Benchmarks (Shared)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: libs/shared
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
      - uses: actions/setup-python@v5
      - run: uv sync --all-extras --dev

      - uses: CodSpeedHQ/action@v3
        with:
          run: DJANGO_SETTINGS_MODULE=shared.django_apps.settings_test uv run --project libs/shared pytest --rootdir=libs/shared libs/shared/tests/benchmarks/ --codspeed
          token: ${{ secrets.CODSPEED_TOKEN }}
