name: Upload Overwatch

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: read

jobs:
  upload-overwatch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [apps/worker, apps/codecov-api, libs/shared]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - uses: astral-sh/setup-uv@v5
      - run: uv sync
        working-directory: ${{ matrix.project }}
      - run: uv pip install mypy==1.15.0 ruff==0.11.8
        working-directory: ${{ matrix.project }}

      - name: Install Overwatch CLI
        run: |
          curl -o overwatch-cli https://overwatch.codecov.io/linux/cli
          chmod +x overwatch-cli
          # Move the CLI to a location accessible from working directories
          mv overwatch-cli /usr/local/bin/overwatch-cli

      - name: Run Overwatch CLI
        working-directory: ${{ matrix.project }}
        run: |
          overwatch-cli \
            --auth-token ${{ secrets.SENTRY_AUTH_TOKEN }} \
            --organization-slug codecov \
            python \
            --python-path .venv/bin/python