name: Upload Overwatch

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: read

jobs:
  upload-overwatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - uses: astral-sh/setup-uv@v5
      - run: uv sync
      
      - name: Install Overwatch CLI
        run: |
          curl -o overwatch-cli https://overwatch.codecov.dev/linux/cli
          chmod +x overwatch-cli
          # Move the CLI to a location accessible from working directories
          mv overwatch-cli /usr/local/bin/overwatch-cli

      - name: Run Overwatch CLI
        run: |
          overwatch-cli \
            --auth-token ${{ secrets.SENTRY_AUTH_TOKEN }} \
            --organization-slug codecov \
            python \
            --python-path .venv/bin/python
